hibernate.connection.driver_class=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.url=jdbc:postgresql://localhost:5433/prueba
hibernate.connection.username=zolrack
hibernate.connection.password=123

hibernate.hbm2ddl.auto=update
# hibernate.show_sql=true

hibernate.format_sql=true
hibernate.use_sql_comments=true

hibernate.validator.apply_to_ddl: false
hibernate.validator.autoregister_listeners: false